INFO 2023-10-06 15:35:19,114 autoreload 7988 2436 Watching for file changes with StatReloader
INFO 2023-10-06 15:35:48,859 autoreload 14876 11728 Watching for file changes with StatReloader
INFO 2023-10-06 15:36:57,990 autoreload 14876 11728 C:\Users\User\PycharmProjects\specialization\django\seminars\project1\baseproject\settings.py changed, reloading.
INFO 2023-10-06 15:36:58,480 autoreload 6544 4460 Watching for file changes with StatReloader
INFO 2023-10-06 15:37:24,476 autoreload 6544 4460 C:\Users\User\PycharmProjects\specialization\django\seminars\project1\testapp\urls.py changed, reloading.
INFO 2023-10-06 15:37:24,909 autoreload 11424 5284 Watching for file changes with StatReloader
INFO 2023-10-06 15:40:18,992 autoreload 11200 9312 Watching for file changes with StatReloader
INFO 2023-10-06 15:40:46,808 autoreload 10624 13160 Watching for file changes with StatReloader
INFO 2023-10-06 15:41:27,351 autoreload 2716 16208 Watching for file changes with StatReloader
INFO 2023-10-06 15:41:28,699 basehttp 2716 15412 "GET / HTTP/1.1" 200 22
WARNING 2023-10-06 15:41:29,066 log 2716 15412 Not Found: /favicon.ico
WARNING 2023-10-06 15:41:29,067 basehttp 2716 15412 "GET /favicon.ico HTTP/1.1" 404 2487
WARNING 2023-10-06 15:41:33,701 log 2716 15412 Not Found: /game1
WARNING 2023-10-06 15:41:33,701 basehttp 2716 15412 "GET /game1 HTTP/1.1" 404 2469
INFO 2023-10-06 15:41:43,221 basehttp 2716 15412 "GET /test/ HTTP/1.1" 200 13
INFO 2023-10-06 15:41:47,310 basehttp 2716 15412 "GET /test/game1 HTTP/1.1" 301 0
ERROR 2023-10-06 15:41:47,380 log 2716 13576 Internal Server Error: /test/game1/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: testapp_eagletails

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\django\seminars\project1\testapp\views.py", line 25, in eagle_or_tails
    res_w.save()
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: testapp_eagletails
ERROR 2023-10-06 15:41:47,394 basehttp 2716 13576 "GET /test/game1/ HTTP/1.1" 500 147505
INFO 2023-10-06 15:41:57,652 basehttp 2716 13576 "GET /games/game2 HTTP/1.1" 301 0
INFO 2023-10-06 15:41:57,660 views 2716 5136 Game 2 is used
INFO 2023-10-06 15:41:57,661 basehttp 2716 5136 "GET /games/game2/ HTTP/1.1" 200 43
INFO 2023-10-06 15:42:02,187 basehttp 2716 5136 "GET /games/game1 HTTP/1.1" 301 0
INFO 2023-10-06 15:42:02,192 views 2716 14884 Game 1 is used
INFO 2023-10-06 15:42:02,193 basehttp 2716 14884 "GET /games/game1/ HTTP/1.1" 200 23
WARNING 2023-10-06 15:42:05,035 log 2716 14884 Not Found: /games/statistic/
WARNING 2023-10-06 15:42:05,036 basehttp 2716 14884 "GET /games/statistic/ HTTP/1.1" 404 2942
ERROR 2023-10-06 15:42:16,234 log 2716 14884 Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 187, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\admin\sites.py", line 261, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\admin\sites.py", line 230, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\admin\sites.py", line 203, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 191, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 53, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 192, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 42, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
ERROR 2023-10-06 15:42:16,242 basehttp 2716 14884 "GET /admin/ HTTP/1.1" 500 201082
ERROR 2023-10-06 15:43:39,899 log 2716 14884 Internal Server Error: /test/game1/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: testapp_eagletails

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\django\seminars\project1\testapp\views.py", line 25, in eagle_or_tails
    res_w.save()
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\specialization\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: testapp_eagletails
ERROR 2023-10-06 15:43:39,899 basehttp 2716 14884 "GET /test/game1/ HTTP/1.1" 500 147505
INFO 2023-10-06 15:44:39,672 autoreload 6396 13248 Watching for file changes with StatReloader
INFO 2023-10-06 15:44:42,284 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:49,286 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:49,930 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:50,663 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:51,278 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:51,783 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:52,165 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:52,345 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:52,550 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:52,740 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:52,917 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:53,263 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:53,443 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:53,608 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:53,797 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:53,959 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:54,175 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:54,342 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:54,550 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:54,724 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:54,926 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:55,107 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:55,309 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:44:55,476 basehttp 6396 5768 "GET /test/game1/ HTTP/1.1" 200 94
INFO 2023-10-06 15:49:28,518 autoreload 10820 14676 Watching for file changes with StatReloader
INFO 2023-10-06 15:49:29,866 basehttp 10820 8196 "GET / HTTP/1.1" 200 22
WARNING 2023-10-06 15:49:30,163 log 10820 8196 Not Found: /favicon.ico
WARNING 2023-10-06 15:49:30,164 basehttp 10820 8196 "GET /favicon.ico HTTP/1.1" 404 2487
INFO 2023-10-06 15:49:36,732 basehttp 10820 8196 "GET /admin/ HTTP/1.1" 302 0
INFO 2023-10-06 15:49:36,766 basehttp 10820 8196 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
INFO 2023-10-06 15:49:42,094 basehttp 10820 8196 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4534
INFO 2023-10-06 15:49:47,389 basehttp 10820 8196 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4534
INFO 2023-10-06 15:53:23,877 autoreload 11240 9772 Watching for file changes with StatReloader
INFO 2023-10-06 15:53:24,724 basehttp 11240 12364 "GET / HTTP/1.1" 200 22
WARNING 2023-10-06 15:53:25,039 log 11240 12364 Not Found: /favicon.ico
WARNING 2023-10-06 15:53:25,039 basehttp 11240 12364 "GET /favicon.ico HTTP/1.1" 404 2487
WARNING 2023-10-06 15:53:26,936 log 11240 12364 Not Found: /about
WARNING 2023-10-06 15:53:26,937 basehttp 11240 12364 "GET /about HTTP/1.1" 404 2469
INFO 2023-10-06 15:53:31,700 basehttp 11240 12364 "GET /admin/ HTTP/1.1" 302 0
INFO 2023-10-06 15:53:31,718 basehttp 11240 12364 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
INFO 2023-10-06 15:53:34,305 basehttp 11240 12364 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4534
INFO 2023-10-06 15:53:38,479 basehttp 11240 12364 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2023-10-06 15:53:38,497 basehttp 11240 12364 "GET /admin/ HTTP/1.1" 200 6570
INFO 2023-10-06 15:53:43,060 basehttp 11240 12364 "GET /admin/testapp/eagletails/ HTTP/1.1" 200 15189
INFO 2023-10-06 15:53:43,092 basehttp 11240 12364 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-06 15:53:55,170 basehttp 11240 12364 "GET /admin/testapp/eagletails/1/change/ HTTP/1.1" 200 10200
INFO 2023-10-06 15:53:55,192 basehttp 11240 12364 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-06 15:54:01,068 basehttp 11240 12364 "GET /admin/testapp/eagletails/ HTTP/1.1" 200 15189
INFO 2023-10-06 15:54:09,264 basehttp 11240 12364 "POST /admin/testapp/eagletails/ HTTP/1.1" 200 8306
INFO 2023-10-06 15:54:10,481 basehttp 11240 12364 "POST /admin/testapp/eagletails/ HTTP/1.1" 302 0
INFO 2023-10-06 15:54:10,494 basehttp 11240 12364 "GET /admin/testapp/eagletails/ HTTP/1.1" 200 14820
INFO 2023-10-06 15:54:10,519 basehttp 11240 12364 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
